# Generated by Django 2.2.5 on 2019-12-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191205_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_pics', verbose_name='Картинка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.Product')),
            ],
        ),
    ]
