# Generated by Django 2.2.5 on 2019-12-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191204_0457'),
        ('webapp', '0003_auto_20191205_0421'),
    ]

    operations = [
    ]
