# Generated by Django 2.2.5 on 2019-12-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_merge_20191216_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories_pics', verbose_name='Картинка категории'),
        ),
    ]
