# Generated by Django 2.2.5 on 2019-12-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('text', models.TextField(max_length=512, verbose_name='Текст')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.Product')),
            ],
        ),
    ]
